### ISSUE TITLE
Smartwatch: Artikel mit Speedreading "vorlesen"

### ISSUE THREAD

**Issue by baba43** [hurt-/RSS-Watch#4]
Artikel sollen aus der Artikelliste ausgewählt werden können und anschließend mithilfe unserer Speedreading Library dargestellt werden, sodass der Nutzer sie lesen kann.

Im ersten Schritt ist keine besondere Navigation notwendig, allerdings sollte der Benutzer das Speedreading zumindest pausieren können (z. B. durch einfache Berührung der Oberfläche, also ohne zusätzlichen Button)

**Comment by AndrejSchaefer** [comment]
reference to #13 (closed), #15 (closed)
requires: #3 (open), #12 (open)
